// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Model.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<char>("MiddleInitial")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("customerOrders");
                });

            modelBuilder.Entity("Model.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrustFlavor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrustType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasChicken")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasExtraCheese")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasOlives")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasOnions")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasPepperoni")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasPineapple")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SauceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("pizzaOrders");
                });

            modelBuilder.Entity("Model.Pizza", b =>
                {
                    b.HasOne("Model.CustomerOrder", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("CustomerOrderId");
                });

            modelBuilder.Entity("Model.CustomerOrder", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
